#influxdb 정보 설정 2022-07-11 by Andrew Kim
spring:
    # influxdb 설정
    influxdb:
        url:
        username:
        password:
        database:
        retention-policy: autogen
        
    # mysql db 설정       
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
        username: 
        password: 
        
# server 설정
server:
    port: 8081
    context-path: /
    encoding:
        charset: UTF-8
        enabled: true
        force: true