#influxdb 정보 설정 2022-07-11 by Andrew Kim
spring:
    # influxdb 설정
    influxdb:
        url:
        username:
        password:
        database:
        retention-policy: autogen
    mvc:
        view:
            prefix: /WEB-INF/jsp
            suffix: .jsp
        
    # mysql db 설정       
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3406/hnt?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
        username: root
        password: ehdus77!@
        
    jackson:
        serialization:
            fail-on-empty-beans: false
        
# server 설정
server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true